// Generates the data files for the web / Android version from the shared sources:
//   web/js/data.js            (config + all translations + all levels, loadable without fetch/CORS)
//   web/manifest.webmanifest  (PWA manifest with the game name from game.json)
// Usage: node tools/build-web.mjs [version]     (version defaults to "0.0.0-dev")
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const config = JSON.parse(read('game.json'));
const version = process.argv[2] || process.env.GAME_VERSION || '0.0.0-dev';

const langIndex = JSON.parse(read('shared/lang/index.json'));
const langs = Object.fromEntries(langIndex.map(c => [c, JSON.parse(read(`shared/lang/${c}.json`))]));
const levelIndex = JSON.parse(read('shared/levels/index.json'));
const levels = Object.fromEntries(levelIndex.map(f => [f, read(`shared/levels/${f}`)]));

const data = { config: { ...config, version }, langIndex, langs, levelIndex, levels };
fs.writeFileSync(path.join(root, 'web/js/data.js'), `// generated by tools/build-web.mjs - do not edit\nwindow.GAME_DATA = ${JSON.stringify(data)};\n`);

const manifest = {
  name: config.name,
  short_name: config.name,
  id: './',
  start_url: './',
  scope: './',
  display: 'fullscreen',
  orientation: 'landscape',
  background_color: '#0a1024',
  theme_color: '#1e3a6e',
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: 'icon.svg', sizes: 'any', type: 'image/svg+xml' },
  ],
};
fs.writeFileSync(path.join(root, 'web/manifest.webmanifest'), JSON.stringify(manifest, null, 2) + '\n');
console.log(`web data built (version ${version}, ${langIndex.length} languages, ${levelIndex.length} levels)`);
