// One-off helper: adds the texts for the online features to all shared/lang/*.json files.
// Existing keys are left untouched, so it can be re-run safely.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../shared/lang');
const keys = ['online.submit', 'online.leaderboard', 'online.account', 'online.nickname', 'online.username', 'online.password', 'online.login',
  'online.register', 'online.logout', 'online.logged_in', 'online.sending', 'online.accepted', 'online.rejected', 'online.error',
  'online.not_configured', 'online.name_invalid', 'online.name_taken', 'online.login_failed', 'online.recovery', 'online.empty',
  'online.hint', 'online.password_rules', 'online.no_run', 'online.too_many', 'online.password_weak', 'online.user_taken',
  'online.by_time', 'online.by_score', 'online.save_tampered'];

const T = {
  en: ['Submit online', 'Online leaderboard', 'Online account', 'Your name for the leaderboard', 'Username', 'Password', 'Log in',
    'Create account', 'Log out', 'Logged in as {0}', 'Verifying your run...', 'Verified! Rank {0} by time, rank {1} by points.', 'This run could not be verified.', 'No connection to the server.',
    'Online features are not set up yet.', 'Name: 3-16 letters or digits.', 'This name is taken or not allowed.', 'Username or password is wrong.', 'Your recovery code - write it down! You need it if you forget your password:', 'No entries yet - be the first!',
    'L / Y: online leaderboard', 'Password: at least 10 characters', 'You were offline when the level started, so this run cannot be submitted.', 'Too many attempts. Please try again later.', 'The password is too short or too easy to guess.', 'This username is not available (3-20 letters, digits, _ or -).',
    'Fastest', 'Most points', 'The save file was modified and has been reset.'],
  fr: ['Envoyer en ligne', 'Classement en ligne', 'Compte en ligne', 'Ton nom pour le classement', "Nom d'utilisateur", 'Mot de passe', 'Se connecter',
    'Créer un compte', 'Se déconnecter', 'Connecté en tant que {0}', 'Vérification de ta partie...', 'Vérifié ! Rang {0} au temps, rang {1} aux points.', "Cette partie n'a pas pu être vérifiée.", 'Pas de connexion au serveur.',
    'Les fonctions en ligne ne sont pas encore configurées.', 'Nom : 3 à 16 lettres ou chiffres.', "Ce nom est déjà pris ou n'est pas autorisé.", "Nom d'utilisateur ou mot de passe incorrect.", "Ton code de récupération – note-le ! Il te faut si tu oublies ton mot de passe :", 'Aucune entrée – sois le premier !',
    'L / Y : classement en ligne', 'Mot de passe : au moins 10 caractères', 'Tu étais hors ligne au début du niveau, cette partie ne peut donc pas être envoyée.', 'Trop de tentatives. Réessaie plus tard.', 'Le mot de passe est trop court ou trop facile à deviner.', "Ce nom d'utilisateur n'est pas disponible (3 à 20 lettres, chiffres, _ ou -).",
    'Plus rapides', 'Plus de points', 'La sauvegarde a été modifiée et a été réinitialisée.'],
  de: ['Online einreichen', 'Online-Bestenliste', 'Online-Konto', 'Dein Name für die Bestenliste', 'Benutzername', 'Passwort', 'Anmelden',
    'Konto erstellen', 'Abmelden', 'Angemeldet als {0}', 'Dein Lauf wird geprüft...', 'Geprüft! Rang {0} nach Zeit, Rang {1} nach Punkten.', 'Dieser Lauf konnte nicht bestätigt werden.', 'Keine Verbindung zum Server.',
    'Die Online-Funktionen sind noch nicht eingerichtet.', 'Name: 3–16 Buchstaben oder Ziffern.', 'Dieser Name ist vergeben oder nicht erlaubt.', 'Benutzername oder Passwort ist falsch.', 'Dein Wiederherstellungs-Code – schreib ihn auf! Du brauchst ihn, wenn du dein Passwort vergisst:', 'Noch keine Einträge – sei die oder der Erste!',
    'L / Y: Online-Bestenliste', 'Passwort: mindestens 10 Zeichen', 'Beim Levelstart warst du offline, darum kann dieser Lauf nicht eingereicht werden.', 'Zu viele Versuche. Bitte später nochmals.', 'Das Passwort ist zu kurz oder zu leicht zu erraten.', 'Dieser Benutzername ist nicht verfügbar (3–20 Buchstaben, Ziffern, _ oder -).',
    'Schnellste', 'Meiste Punkte', 'Der Spielstand wurde verändert und wurde zurückgesetzt.'],
  gsw: ['Online iiräiche', 'Online-Bestelischte', 'Online-Konto', 'Din Name für d Bestelischte', 'Benutzername', 'Passwort', 'Aamälde',
    'Konto erstelle', 'Abmälde', 'Aagmäldet als {0}', 'Din Lauf wird prüeft...', 'Prüeft! Rang {0} noch Ziit, Rang {1} noch Pünkt.', 'Dä Lauf het nöd chöne bestätigt wärde.', 'Kei Verbindig zum Server.',
    'D Online-Funktione sind no nöd iigrichtet.', 'Name: 3–16 Buechstabe oder Ziffere.', 'Dä Name isch vergäh oder nöd erlaubt.', 'Benutzername oder Passwort isch falsch.', 'Din Widerherstelligs-Code – schriib en uf! Du bruuchsch en, wänn d s Passwort vergisch:', 'No kei Iiträg – bis du dä Erscht!',
    'L / Y: Online-Bestelischte', 'Passwort: mindeschtens 10 Zeiche', 'Bim Levelstart bisch offline gsi, drum cha dä Lauf nöd iigreicht wärde.', 'Z vill Versüech. Bitte spöter nomal.', 'S Passwort isch z churz oder z eifach.', 'Dä Benutzername isch nöd verfüegbar (3–20 Buechstabe, Ziffere, _ oder -).',
    'Schnällschti', 'Meischti Pünkt', 'Dä Spielstand isch veränderet worde und isch zruggsetzt worde.'],
  es: ['Enviar en línea', 'Clasificación en línea', 'Cuenta en línea', 'Tu nombre para la clasificación', 'Usuario', 'Contraseña', 'Iniciar sesión',
    'Crear cuenta', 'Cerrar sesión', 'Conectado como {0}', 'Verificando tu partida...', '¡Verificado! Puesto {0} por tiempo, puesto {1} por puntos.', 'No se pudo verificar esta partida.', 'Sin conexión con el servidor.',
    'Las funciones en línea aún no están configuradas.', 'Nombre: de 3 a 16 letras o números.', 'Este nombre está ocupado o no está permitido.', 'Usuario o contraseña incorrectos.', 'Tu código de recuperación: ¡anótalo! Lo necesitas si olvidas tu contraseña:', 'Aún no hay entradas. ¡Sé el primero!',
    'L / Y: clasificación en línea', 'Contraseña: al menos 10 caracteres', 'Estabas sin conexión al empezar el nivel, así que esta partida no se puede enviar.', 'Demasiados intentos. Inténtalo más tarde.', 'La contraseña es demasiado corta o fácil de adivinar.', 'Este usuario no está disponible (3-20 letras, números, _ o -).',
    'Más rápidos', 'Más puntos', 'La partida guardada fue modificada y se ha restablecido.'],
  it: ['Invia online', 'Classifica online', 'Account online', 'Il tuo nome per la classifica', 'Nome utente', 'Password', 'Accedi',
    'Crea account', 'Esci', 'Connesso come {0}', 'Verifica della partita...', 'Verificato! Posizione {0} per tempo, {1} per punti.', 'Non è stato possibile verificare questa partita.', 'Nessuna connessione al server.',
    'Le funzioni online non sono ancora configurate.', 'Nome: da 3 a 16 lettere o cifre.', 'Questo nome è già usato o non è consentito.', 'Nome utente o password errati.', 'Il tuo codice di recupero: annotalo! Ti serve se dimentichi la password:', 'Ancora nessuna voce: sii il primo!',
    'L / Y: classifica online', 'Password: almeno 10 caratteri', "Eri offline all'inizio del livello, quindi questa partita non può essere inviata.", 'Troppi tentativi. Riprova più tardi.', 'La password è troppo corta o troppo facile.', 'Questo nome utente non è disponibile (3-20 lettere, cifre, _ o -).',
    'Più veloci', 'Più punti', 'Il salvataggio è stato modificato ed è stato azzerato.'],
  pt: ['Enviar online', 'Classificação online', 'Conta online', 'O teu nome para a classificação', 'Utilizador', 'Palavra-passe', 'Entrar',
    'Criar conta', 'Sair', 'Ligado como {0}', 'A verificar a tua partida...', 'Verificado! Posição {0} por tempo, {1} por pontos.', 'Não foi possível verificar esta partida.', 'Sem ligação ao servidor.',
    'As funções online ainda não estão configuradas.', 'Nome: 3 a 16 letras ou números.', 'Este nome já está ocupado ou não é permitido.', 'Utilizador ou palavra-passe incorretos.', 'O teu código de recuperação – aponta-o! Precisas dele se esqueceres a palavra-passe:', 'Ainda sem entradas – sê o primeiro!',
    'L / Y: classificação online', 'Palavra-passe: pelo menos 10 caracteres', 'Estavas offline no início do nível, por isso esta partida não pode ser enviada.', 'Demasiadas tentativas. Tenta mais tarde.', 'A palavra-passe é demasiado curta ou fácil.', 'Este utilizador não está disponível (3-20 letras, números, _ ou -).',
    'Mais rápidos', 'Mais pontos', 'O jogo guardado foi alterado e foi reposto.'],
  nl: ['Online insturen', 'Online ranglijst', 'Online account', 'Je naam voor de ranglijst', 'Gebruikersnaam', 'Wachtwoord', 'Inloggen',
    'Account maken', 'Uitloggen', 'Ingelogd als {0}', 'Je run wordt gecontroleerd...', 'Gecontroleerd! Plaats {0} op tijd, plaats {1} op punten.', 'Deze run kon niet worden bevestigd.', 'Geen verbinding met de server.',
    'De online functies zijn nog niet ingesteld.', 'Naam: 3-16 letters of cijfers.', 'Deze naam is bezet of niet toegestaan.', 'Gebruikersnaam of wachtwoord onjuist.', 'Je herstelcode – schrijf hem op! Je hebt hem nodig als je je wachtwoord vergeet:', 'Nog geen inzendingen – wees de eerste!',
    'L / Y: online ranglijst', 'Wachtwoord: minstens 10 tekens', 'Je was offline toen het level begon, dus deze run kan niet worden ingestuurd.', 'Te veel pogingen. Probeer het later opnieuw.', 'Het wachtwoord is te kort of te makkelijk.', 'Deze gebruikersnaam is niet beschikbaar (3-20 letters, cijfers, _ of -).',
    'Snelste', 'Meeste punten', 'Het opslagbestand is gewijzigd en is teruggezet.'],
  sv: ['Skicka in online', 'Topplista online', 'Onlinekonto', 'Ditt namn på topplistan', 'Användarnamn', 'Lösenord', 'Logga in',
    'Skapa konto', 'Logga ut', 'Inloggad som {0}', 'Ditt lopp kontrolleras...', 'Godkänt! Plats {0} på tid, plats {1} på poäng.', 'Loppet kunde inte bekräftas.', 'Ingen anslutning till servern.',
    'Onlinefunktionerna är inte inställda än.', 'Namn: 3–16 bokstäver eller siffror.', 'Namnet är upptaget eller inte tillåtet.', 'Fel användarnamn eller lösenord.', 'Din återställningskod – skriv ner den! Du behöver den om du glömmer lösenordet:', 'Inga resultat än – bli först!',
    'L / Y: topplista online', 'Lösenord: minst 10 tecken', 'Du var offline när banan startade, så loppet kan inte skickas in.', 'För många försök. Försök igen senare.', 'Lösenordet är för kort eller för lätt att gissa.', 'Användarnamnet är inte tillgängligt (3–20 bokstäver, siffror, _ eller -).',
    'Snabbast', 'Flest poäng', 'Sparfilen har ändrats och har återställts.'],
  pl: ['Wyślij online', 'Ranking online', 'Konto online', 'Twoja nazwa w rankingu', 'Nazwa użytkownika', 'Hasło', 'Zaloguj',
    'Utwórz konto', 'Wyloguj', 'Zalogowano jako {0}', 'Sprawdzanie przejścia...', 'Zweryfikowano! Miejsce {0} za czas, {1} za punkty.', 'Nie udało się zweryfikować tego przejścia.', 'Brak połączenia z serwerem.',
    'Funkcje online nie są jeszcze skonfigurowane.', 'Nazwa: 3–16 liter lub cyfr.', 'Ta nazwa jest zajęta lub niedozwolona.', 'Błędna nazwa użytkownika lub hasło.', 'Twój kod odzyskiwania – zapisz go! Przyda się, gdy zapomnisz hasła:', 'Brak wpisów – bądź pierwszy!',
    'L / Y: ranking online', 'Hasło: co najmniej 10 znaków', 'Na początku poziomu byłeś offline, więc tego przejścia nie można wysłać.', 'Zbyt wiele prób. Spróbuj później.', 'Hasło jest za krótkie lub zbyt łatwe.', 'Ta nazwa użytkownika jest niedostępna (3–20 liter, cyfr, _ lub -).',
    'Najszybsi', 'Najwięcej punktów', 'Zapis gry został zmieniony i zresetowany.'],
  cs: ['Odeslat online', 'Online žebříček', 'Online účet', 'Tvé jméno v žebříčku', 'Uživatelské jméno', 'Heslo', 'Přihlásit',
    'Vytvořit účet', 'Odhlásit', 'Přihlášen jako {0}', 'Ověřuji tvůj průchod...', 'Ověřeno! {0}. místo podle času, {1}. podle bodů.', 'Tento průchod se nepodařilo ověřit.', 'Žádné spojení se serverem.',
    'Online funkce ještě nejsou nastavené.', 'Jméno: 3–16 písmen nebo číslic.', 'Toto jméno je obsazené nebo není povolené.', 'Špatné jméno nebo heslo.', 'Tvůj obnovovací kód – zapiš si ho! Budeš ho potřebovat, když zapomeneš heslo:', 'Zatím žádné záznamy – buď první!',
    'L / Y: online žebříček', 'Heslo: alespoň 10 znaků', 'Na začátku úrovně jsi byl offline, proto tento průchod nelze odeslat.', 'Příliš mnoho pokusů. Zkus to později.', 'Heslo je příliš krátké nebo snadné.', 'Toto jméno není k dispozici (3–20 písmen, číslic, _ nebo -).',
    'Nejrychlejší', 'Nejvíc bodů', 'Uložená hra byla změněna a byla obnovena.'],
  tr: ['Çevrimiçi gönder', 'Çevrimiçi sıralama', 'Çevrimiçi hesap', 'Sıralama için adın', 'Kullanıcı adı', 'Şifre', 'Giriş yap',
    'Hesap oluştur', 'Çıkış yap', '{0} olarak giriş yapıldı', 'Oyunun doğrulanıyor...', 'Doğrulandı! Sürede {0}., puanda {1}. sıradasın.', 'Bu oyun doğrulanamadı.', 'Sunucuya bağlantı yok.',
    'Çevrimiçi özellikler henüz ayarlanmadı.', 'Ad: 3–16 harf veya rakam.', 'Bu ad alınmış ya da izin verilmiyor.', 'Kullanıcı adı veya şifre yanlış.', 'Kurtarma kodun – bir yere yaz! Şifreni unutursan gerekecek:', 'Henüz kayıt yok – ilk sen ol!',
    'L / Y: çevrimiçi sıralama', 'Şifre: en az 10 karakter', 'Bölüm başladığında çevrimdışıydın, bu yüzden bu oyun gönderilemez.', 'Çok fazla deneme. Lütfen daha sonra tekrar dene.', 'Şifre çok kısa ya da tahmin etmesi çok kolay.', 'Bu kullanıcı adı kullanılamaz (3–20 harf, rakam, _ veya -).',
    'En hızlılar', 'En çok puan', 'Kayıt dosyası değiştirilmiş ve sıfırlandı.'],
  ru: ['Отправить онлайн', 'Онлайн-рейтинг', 'Онлайн-аккаунт', 'Твоё имя в рейтинге', 'Имя пользователя', 'Пароль', 'Войти',
    'Создать аккаунт', 'Выйти', 'Вы вошли как {0}', 'Проверяем твой забег...', 'Проверено! Место {0} по времени, место {1} по очкам.', 'Не удалось подтвердить этот забег.', 'Нет соединения с сервером.',
    'Онлайн-функции ещё не настроены.', 'Имя: 3–16 букв или цифр.', 'Это имя занято или запрещено.', 'Неверное имя пользователя или пароль.', 'Твой код восстановления – запиши его! Он нужен, если забудешь пароль:', 'Пока нет записей – будь первым!',
    'L / Y: онлайн-рейтинг', 'Пароль: не менее 10 символов', 'В начале уровня ты был офлайн, поэтому этот забег нельзя отправить.', 'Слишком много попыток. Попробуй позже.', 'Пароль слишком короткий или простой.', 'Это имя недоступно (3–20 букв, цифр, _ или -).',
    'Самые быстрые', 'Больше всего очков', 'Файл сохранения был изменён и сброшен.'],
  el: ['Υποβολή online', 'Online κατάταξη', 'Λογαριασμός online', 'Το όνομά σου για την κατάταξη', 'Όνομα χρήστη', 'Κωδικός', 'Σύνδεση',
    'Δημιουργία λογαριασμού', 'Αποσύνδεση', 'Συνδεδεμένος ως {0}', 'Έλεγχος της διαδρομής σου...', 'Επαληθεύτηκε! Θέση {0} σε χρόνο, θέση {1} σε πόντους.', 'Η διαδρομή δεν μπόρεσε να επαληθευτεί.', 'Δεν υπάρχει σύνδεση με τον διακομιστή.',
    'Οι online λειτουργίες δεν έχουν ρυθμιστεί ακόμη.', 'Όνομα: 3–16 γράμματα ή ψηφία.', 'Το όνομα είναι πιασμένο ή δεν επιτρέπεται.', 'Λάθος όνομα χρήστη ή κωδικός.', 'Ο κωδικός ανάκτησης – σημείωσέ τον! Θα τον χρειαστείς αν ξεχάσεις τον κωδικό σου:', 'Καμία καταχώριση ακόμη – γίνε ο πρώτος!',
    'L / Y: online κατάταξη', 'Κωδικός: τουλάχιστον 10 χαρακτήρες', 'Ήσουν εκτός σύνδεσης στην αρχή της πίστας, γι’ αυτό η διαδρομή δεν μπορεί να υποβληθεί.', 'Πάρα πολλές προσπάθειες. Δοκίμασε αργότερα.', 'Ο κωδικός είναι πολύ σύντομος ή εύκολος.', 'Το όνομα χρήστη δεν είναι διαθέσιμο (3–20 γράμματα, ψηφία, _ ή -).',
    'Ταχύτεροι', 'Περισσότεροι πόντοι', 'Το αρχείο αποθήκευσης τροποποιήθηκε και επαναφέρθηκε.'],
  ja: ['オンラインに送信', 'オンラインランキング', 'オンラインアカウント', 'ランキングに表示する名前', 'ユーザー名', 'パスワード', 'ログイン',
    'アカウント作成', 'ログアウト', '{0} としてログイン中', 'プレイを確認しています...', '確認しました！タイム {0} 位、スコア {1} 位。', 'このプレイは確認できませんでした。', 'サーバーに接続できません。',
    'オンライン機能はまだ設定されていません。', '名前：3〜16文字の英数字か文字。', 'この名前は使用中か、使用できません。', 'ユーザー名かパスワードが違います。', '復元コードです。必ずメモしてください！パスワードを忘れたときに必要です：', 'まだ記録がありません。一番乗りを目指そう！',
    'L / Y：オンラインランキング', 'パスワード：10文字以上', 'レベル開始時にオフラインだったため、このプレイは送信できません。', '試行回数が多すぎます。しばらくしてから再試行してください。', 'パスワードが短すぎるか、推測されやすすぎます。', 'このユーザー名は使えません（3〜20文字の英数字、_、-）。',
    '最速', '最高スコア', 'セーブデータが改ざんされていたため、リセットしました。'],
  zh: ['在线提交', '在线排行榜', '在线账户', '你在排行榜上的名字', '用户名', '密码', '登录',
    '创建账户', '退出登录', '已登录：{0}', '正在验证你的成绩...', '验证成功！用时排名第 {0}，分数排名第 {1}。', '无法验证这次成绩。', '无法连接服务器。',
    '在线功能尚未设置。', '名字：3–16 个字母或数字。', '这个名字已被使用或不被允许。', '用户名或密码错误。', '你的恢复码——请记下来！忘记密码时需要它：', '还没有记录——争当第一名吧！',
    'L / Y：在线排行榜', '密码：至少 10 个字符', '关卡开始时你处于离线状态，因此无法提交这次成绩。', '尝试次数过多，请稍后再试。', '密码太短或太容易被猜到。', '这个用户名不可用（3–20 个字母、数字、_ 或 -）。',
    '最快', '最高分', '存档已被修改，已重置。'],
  ko: ['온라인 제출', '온라인 순위표', '온라인 계정', '순위표에 표시할 이름', '사용자 이름', '비밀번호', '로그인',
    '계정 만들기', '로그아웃', '{0}(으)로 로그인됨', '기록을 확인하는 중...', '확인 완료! 시간 {0}위, 점수 {1}위.', '이 기록을 확인할 수 없습니다.', '서버에 연결할 수 없습니다.',
    '온라인 기능이 아직 설정되지 않았습니다.', '이름: 3~16자의 문자 또는 숫자.', '이미 사용 중이거나 허용되지 않는 이름입니다.', '사용자 이름 또는 비밀번호가 틀렸습니다.', '복구 코드입니다. 꼭 적어 두세요! 비밀번호를 잊었을 때 필요합니다:', '아직 기록이 없습니다. 첫 번째가 되어 보세요!',
    'L / Y: 온라인 순위표', '비밀번호: 10자 이상', '레벨을 시작할 때 오프라인이었기 때문에 이 기록은 제출할 수 없습니다.', '시도 횟수가 너무 많습니다. 나중에 다시 시도하세요.', '비밀번호가 너무 짧거나 추측하기 쉽습니다.', '사용할 수 없는 사용자 이름입니다 (3~20자의 문자, 숫자, _ 또는 -).',
    '가장 빠름', '최고 점수', '저장 파일이 변경되어 초기화되었습니다.'],
};

for (const [code, values] of Object.entries(T)) {
  if (values.length !== keys.length) throw new Error(`${code}: ${values.length} texts, expected ${keys.length}`);
  const file = path.join(dir, `${code}.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  keys.forEach((k, i) => { if (!(k in data)) data[k] = values[i]; });
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + '\n');
}
console.log(`added ${keys.length} online texts to ${Object.keys(T).length} languages`);
