// One-off helper: adds the level editor / community texts to all shared/lang/*.json files (existing keys stay).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../shared/lang');
const TOOLS = ['ground', 'brick', 'coinblock', 'coin', 'oneway', 'crumble', 'spikes', 'liquid', 'spring', 'platform', 'platformv', 'fish', 'snowflake', 'wings',
  'heart', 'checkpoint', 'walker', 'spiky', 'bird', 'hopper', 'icicle', 'start', 'goal', 'eraser', 'hand', 'sign'];

const L = {
  en: {
    'community.title': 'Community levels', 'community.search': 'Search', 'community.empty': 'No levels yet - build the first one!', 'community.by': 'by {0}',
    'community.like': 'Like', 'community.report': 'Report', 'community.report_reason': 'What is wrong with this level?', 'community.reported': 'Thank you, we will check it.',
    'community.login_needed': 'Log in to like levels (Options → Online account).', 'online.by_top': 'Most liked', 'online.by_new': 'Newest', 'online.by_plays': 'Most played',
    'editor.title': 'Level editor', 'editor.new': 'New level', 'editor.untitled': 'My level', 'editor.rename': 'Level name', 'editor.world': 'World', 'editor.test': 'Test',
    'editor.save': 'Save', 'editor.publish': 'Publish', 'editor.saved': 'Saved.', 'editor.saved_local': 'Saved on this device. Log in to save online and publish.',
    'editor.need_start': 'Place exactly one start (penguin).', 'editor.need_goal': 'Place exactly one goal (igloo).', 'editor.too_small': 'The level must be at least 20 tiles wide.',
    'editor.title_short': 'Give your level a name (at least 3 characters).', 'editor.publish_info': 'To publish, play your level to the goal once. Good luck!',
    'editor.published': 'Published! Everyone can play your level now.', 'editor.published_main': 'Main level published - active for all players.',
    'editor.not_finished': 'Not finished - reach the goal to publish.', 'editor.login_needed': 'Log in (Options → Online account) to save online and publish.',
    'editor.testing': 'Test run', 'editor.test_ok': 'Goal reached - your level can be finished!', 'editor.hint': 'Left: place · Right: erase · Wheel/arrows: scroll',
    'editor.admin': 'Main level {0} (admin)', 'editor.admin_login': 'Please log in to the admin panel first.', 'editor.not_found': 'Level not found.',
    'editor.too_many': 'You have reached the maximum number of levels.', 'editor.draft_changed': 'The level changed during the test - please test again.',
    'editor.status_local': 'only on this device', 'editor.status_draft': 'draft', 'editor.status_published': 'published', 'editor.status_hidden': 'hidden by a moderator',
    tools: ['Ground', 'Ice brick', 'Coin block', 'Coin', 'Platform', 'Crumbling ice', 'Spikes', 'Lava / water', 'Spring', 'Moving platform ↔', 'Moving platform ↕',
      'Fish block', 'Snowflake block', 'Wing block', 'Heart block', 'Checkpoint', 'Walker', 'Spiky', 'Bird', 'Hopper', 'Icicle', 'Start', 'Goal (igloo)', 'Eraser', 'Move view', 'Sign'],
  },
  fr: {
    'community.title': 'Niveaux de la communauté', 'community.search': 'Chercher', 'community.empty': 'Aucun niveau – crée le premier !', 'community.by': 'par {0}',
    'community.like': "J'aime", 'community.report': 'Signaler', 'community.report_reason': "Qu'est-ce qui ne va pas avec ce niveau ?", 'community.reported': 'Merci, nous allons vérifier.',
    'community.login_needed': 'Connecte-toi pour aimer des niveaux (Options → Compte en ligne).', 'online.by_top': 'Les plus aimés', 'online.by_new': 'Les plus récents', 'online.by_plays': 'Les plus joués',
    'editor.title': 'Éditeur de niveaux', 'editor.new': 'Nouveau niveau', 'editor.untitled': 'Mon niveau', 'editor.rename': 'Nom du niveau', 'editor.world': 'Monde', 'editor.test': 'Tester',
    'editor.save': 'Enregistrer', 'editor.publish': 'Publier', 'editor.saved': 'Enregistré.', 'editor.saved_local': 'Enregistré sur cet appareil. Connecte-toi pour enregistrer en ligne et publier.',
    'editor.need_start': 'Place exactement un départ (pingouin).', 'editor.need_goal': 'Place exactement une arrivée (igloo).', 'editor.too_small': 'Le niveau doit faire au moins 20 cases de large.',
    'editor.title_short': 'Donne un nom à ton niveau (au moins 3 caractères).', 'editor.publish_info': "Pour publier, termine ton niveau une fois jusqu'à l'arrivée. Bonne chance !",
    'editor.published': 'Publié ! Tout le monde peut jouer ton niveau.', 'editor.published_main': 'Niveau principal publié – actif pour tous les joueurs.',
    'editor.not_finished': "Pas terminé – atteins l'arrivée pour publier.", 'editor.login_needed': 'Connecte-toi (Options → Compte en ligne) pour enregistrer en ligne et publier.',
    'editor.testing': "Essai", 'editor.test_ok': "Arrivée atteinte – ton niveau est faisable !", 'editor.hint': 'Gauche : placer · Droite : effacer · Molette/flèches : défiler',
    'editor.admin': 'Niveau principal {0} (admin)', 'editor.admin_login': "Connecte-toi d'abord au panneau d'administration.", 'editor.not_found': 'Niveau introuvable.',
    'editor.too_many': 'Tu as atteint le nombre maximum de niveaux.', 'editor.draft_changed': "Le niveau a changé pendant l'essai – teste à nouveau.",
    'editor.status_local': 'seulement sur cet appareil', 'editor.status_draft': 'brouillon', 'editor.status_published': 'publié', 'editor.status_hidden': 'masqué par un modérateur',
    tools: ['Sol', 'Brique de glace', 'Bloc à pièce', 'Pièce', 'Plateforme', 'Glace fragile', 'Pics', 'Lave / eau', 'Ressort', 'Plateforme mobile ↔', 'Plateforme mobile ↕',
      'Bloc poisson', 'Bloc flocon', 'Bloc ailes', 'Bloc cœur', 'Point de contrôle', 'Marcheur', 'Piquant', 'Oiseau', 'Sauteur', 'Stalactite', 'Départ', 'Arrivée (igloo)', 'Gomme', 'Déplacer la vue', 'Panneau'],
  },
  de: {
    'community.title': 'Community-Level', 'community.search': 'Suchen', 'community.empty': 'Noch keine Level – bau das erste!', 'community.by': 'von {0}',
    'community.like': 'Gefällt mir', 'community.report': 'Melden', 'community.report_reason': 'Was stimmt mit diesem Level nicht?', 'community.reported': 'Danke, wir schauen es uns an.',
    'community.login_needed': 'Melde dich an, um Level zu liken (Optionen → Online-Konto).', 'online.by_top': 'Beliebteste', 'online.by_new': 'Neueste', 'online.by_plays': 'Meistgespielte',
    'editor.title': 'Level-Editor', 'editor.new': 'Neues Level', 'editor.untitled': 'Mein Level', 'editor.rename': 'Name des Levels', 'editor.world': 'Welt', 'editor.test': 'Testen',
    'editor.save': 'Speichern', 'editor.publish': 'Veröffentlichen', 'editor.saved': 'Gespeichert.', 'editor.saved_local': 'Auf diesem Gerät gespeichert. Melde dich an, um online zu speichern und zu veröffentlichen.',
    'editor.need_start': 'Setze genau einen Start (Pinguin).', 'editor.need_goal': 'Setze genau ein Ziel (Iglu).', 'editor.too_small': 'Das Level muss mindestens 20 Felder breit sein.',
    'editor.title_short': 'Gib deinem Level einen Namen (mindestens 3 Zeichen).', 'editor.publish_info': 'Zum Veröffentlichen spielst du dein Level einmal bis ins Ziel. Viel Glück!',
    'editor.published': 'Veröffentlicht! Alle können dein Level jetzt spielen.', 'editor.published_main': 'Hauptlevel veröffentlicht – für alle Spieler aktiv.',
    'editor.not_finished': 'Nicht geschafft – erreiche das Ziel, um zu veröffentlichen.', 'editor.login_needed': 'Melde dich an (Optionen → Online-Konto), um online zu speichern und zu veröffentlichen.',
    'editor.testing': 'Testlauf', 'editor.test_ok': 'Ziel erreicht – dein Level ist schaffbar!', 'editor.hint': 'Links: setzen · Rechts: löschen · Mausrad/Pfeile: scrollen',
    'editor.admin': 'Hauptlevel {0} (Admin)', 'editor.admin_login': 'Bitte zuerst im Admin-Panel anmelden.', 'editor.not_found': 'Level nicht gefunden.',
    'editor.too_many': 'Du hast die maximale Anzahl Level erreicht.', 'editor.draft_changed': 'Das Level wurde während des Tests geändert – bitte nochmals testen.',
    'editor.status_local': 'nur auf diesem Gerät', 'editor.status_draft': 'Entwurf', 'editor.status_published': 'veröffentlicht', 'editor.status_hidden': 'von einem Moderator ausgeblendet',
    tools: ['Boden', 'Eisblock', 'Münzblock', 'Münze', 'Plattform', 'Brüchiges Eis', 'Stacheln', 'Lava / Wasser', 'Feder', 'Bewegliche Plattform ↔', 'Bewegliche Plattform ↕',
      'Fisch-Block', 'Schneeflocken-Block', 'Flügel-Block', 'Herz-Block', 'Checkpoint', 'Läufer', 'Stachler', 'Vogel', 'Hüpfer', 'Eiszapfen', 'Start', 'Ziel (Iglu)', 'Radiergummi', 'Ansicht verschieben', 'Schild'],
  },
  gsw: {
    'community.title': 'Community-Level', 'community.search': 'Sueche', 'community.empty': 'No kei Level – bau s erschte!', 'community.by': 'vo {0}',
    'community.like': 'Gfallt mer', 'community.report': 'Mälde', 'community.report_reason': 'Was stimmt mit dem Level nöd?', 'community.reported': 'Merci, mir lueged s aa.',
    'community.login_needed': 'Mäld di aa, zum Level liike (Optione → Online-Konto).', 'online.by_top': 'Beliebtischti', 'online.by_new': 'Neuschti', 'online.by_plays': 'Meischtgspielti',
    'editor.title': 'Level-Editor', 'editor.new': 'Neus Level', 'editor.untitled': 'Mis Level', 'editor.rename': 'Name vom Level', 'editor.world': 'Wält', 'editor.test': 'Teschte',
    'editor.save': 'Speichere', 'editor.publish': 'Veröffentliche', 'editor.saved': 'Gspeicheret.', 'editor.saved_local': 'Uf dem Grät gspeicheret. Mäld di aa zum online speichere und veröffentliche.',
    'editor.need_start': 'Setz genau ein Start (Pinguin).', 'editor.need_goal': 'Setz genau eis Ziel (Iglu).', 'editor.too_small': 'S Level mues mindeschtens 20 Fälder breit sii.',
    'editor.title_short': 'Gib dim Level en Name (mindeschtens 3 Zeiche).', 'editor.publish_info': 'Zum Veröffentliche spielsch dis Level eimal bis is Ziel. Vill Glück!',
    'editor.published': 'Veröffentlicht! Alli chönd dis Level jetzt spiele.', 'editor.published_main': 'Hauptlevel veröffentlicht – für alli Spieler aktiv.',
    'editor.not_finished': 'Nöd gschafft – erreich s Ziel zum Veröffentliche.', 'editor.login_needed': 'Mäld di aa (Optione → Online-Konto) zum online speichere und veröffentliche.',
    'editor.testing': 'Testlauf', 'editor.test_ok': 'Ziel erreicht – dis Level isch schaffbar!', 'editor.hint': 'Links: setze · Rächts: lösche · Muusrad/Pfiil: scrolle',
    'editor.admin': 'Hauptlevel {0} (Admin)', 'editor.admin_login': 'Bitte zerscht im Admin-Panel aamälde.', 'editor.not_found': 'Level nöd gfunde.',
    'editor.too_many': 'Du hesch di maximal Aazahl Level erreicht.', 'editor.draft_changed': 'S Level isch während em Test gänderet worde – bitte nomal teschte.',
    'editor.status_local': 'nur uf dem Grät', 'editor.status_draft': 'Entwurf', 'editor.status_published': 'veröffentlicht', 'editor.status_hidden': 'vomene Moderator usbländet',
    tools: ['Bode', 'Iisblock', 'Münzblock', 'Münze', 'Plattform', 'Brüchigs Iis', 'Stachle', 'Lava / Wasser', 'Fädere', 'Bewegligi Plattform ↔', 'Bewegligi Plattform ↕',
      'Fisch-Block', 'Schneeflocke-Block', 'Flügel-Block', 'Härz-Block', 'Checkpoint', 'Laufer', 'Stachler', 'Vogel', 'Hüpfer', 'Iiszapfe', 'Start', 'Ziel (Iglu)', 'Radiergummi', 'Asicht verschiebe', 'Schild'],
  },
  es: {
    'community.title': 'Niveles de la comunidad', 'community.search': 'Buscar', 'community.empty': 'Aún no hay niveles. ¡Crea el primero!', 'community.by': 'de {0}',
    'community.like': 'Me gusta', 'community.report': 'Denunciar', 'community.report_reason': '¿Qué problema tiene este nivel?', 'community.reported': 'Gracias, lo revisaremos.',
    'community.login_needed': 'Inicia sesión para dar me gusta (Opciones → Cuenta en línea).', 'online.by_top': 'Más gustados', 'online.by_new': 'Más nuevos', 'online.by_plays': 'Más jugados',
    'editor.title': 'Editor de niveles', 'editor.new': 'Nuevo nivel', 'editor.untitled': 'Mi nivel', 'editor.rename': 'Nombre del nivel', 'editor.world': 'Mundo', 'editor.test': 'Probar',
    'editor.save': 'Guardar', 'editor.publish': 'Publicar', 'editor.saved': 'Guardado.', 'editor.saved_local': 'Guardado en este dispositivo. Inicia sesión para guardar en línea y publicar.',
    'editor.need_start': 'Coloca exactamente una salida (pingüino).', 'editor.need_goal': 'Coloca exactamente una meta (iglú).', 'editor.too_small': 'El nivel debe tener al menos 20 casillas de ancho.',
    'editor.title_short': 'Ponle un nombre a tu nivel (al menos 3 caracteres).', 'editor.publish_info': 'Para publicar, juega tu nivel una vez hasta la meta. ¡Suerte!',
    'editor.published': '¡Publicado! Todos pueden jugar tu nivel.', 'editor.published_main': 'Nivel principal publicado: activo para todos.',
    'editor.not_finished': 'No completado: llega a la meta para publicar.', 'editor.login_needed': 'Inicia sesión (Opciones → Cuenta en línea) para guardar en línea y publicar.',
    'editor.testing': 'Prueba', 'editor.test_ok': '¡Meta alcanzada: tu nivel se puede completar!', 'editor.hint': 'Izq.: colocar · Der.: borrar · Rueda/flechas: desplazar',
    'editor.admin': 'Nivel principal {0} (admin)', 'editor.admin_login': 'Inicia sesión primero en el panel de administración.', 'editor.not_found': 'Nivel no encontrado.',
    'editor.too_many': 'Has alcanzado el número máximo de niveles.', 'editor.draft_changed': 'El nivel cambió durante la prueba: vuelve a probar.',
    'editor.status_local': 'solo en este dispositivo', 'editor.status_draft': 'borrador', 'editor.status_published': 'publicado', 'editor.status_hidden': 'oculto por un moderador',
    tools: ['Suelo', 'Bloque de hielo', 'Bloque de moneda', 'Moneda', 'Plataforma', 'Hielo frágil', 'Pinchos', 'Lava / agua', 'Muelle', 'Plataforma móvil ↔', 'Plataforma móvil ↕',
      'Bloque pez', 'Bloque copo', 'Bloque alas', 'Bloque corazón', 'Punto de control', 'Caminante', 'Pinchudo', 'Pájaro', 'Saltarín', 'Carámbano', 'Salida', 'Meta (iglú)', 'Borrador', 'Mover vista', 'Cartel'],
  },
  it: {
    'community.title': 'Livelli della community', 'community.search': 'Cerca', 'community.empty': 'Ancora nessun livello: crea il primo!', 'community.by': 'di {0}',
    'community.like': 'Mi piace', 'community.report': 'Segnala', 'community.report_reason': 'Cosa non va in questo livello?', 'community.reported': 'Grazie, lo controlleremo.',
    'community.login_needed': 'Accedi per mettere mi piace (Opzioni → Account online).', 'online.by_top': 'Più apprezzati', 'online.by_new': 'Più recenti', 'online.by_plays': 'Più giocati',
    'editor.title': 'Editor di livelli', 'editor.new': 'Nuovo livello', 'editor.untitled': 'Il mio livello', 'editor.rename': 'Nome del livello', 'editor.world': 'Mondo', 'editor.test': 'Prova',
    'editor.save': 'Salva', 'editor.publish': 'Pubblica', 'editor.saved': 'Salvato.', 'editor.saved_local': 'Salvato su questo dispositivo. Accedi per salvare online e pubblicare.',
    'editor.need_start': 'Metti esattamente una partenza (pinguino).', 'editor.need_goal': 'Metti esattamente un traguardo (igloo).', 'editor.too_small': 'Il livello deve essere largo almeno 20 caselle.',
    'editor.title_short': 'Dai un nome al tuo livello (almeno 3 caratteri).', 'editor.publish_info': 'Per pubblicare, completa il tuo livello una volta fino al traguardo. Buona fortuna!',
    'editor.published': 'Pubblicato! Tutti possono giocare il tuo livello.', 'editor.published_main': 'Livello principale pubblicato: attivo per tutti.',
    'editor.not_finished': 'Non completato: raggiungi il traguardo per pubblicare.', 'editor.login_needed': 'Accedi (Opzioni → Account online) per salvare online e pubblicare.',
    'editor.testing': 'Prova', 'editor.test_ok': 'Traguardo raggiunto: il tuo livello è completabile!', 'editor.hint': 'Sinistro: metti · Destro: cancella · Rotella/frecce: scorri',
    'editor.admin': 'Livello principale {0} (admin)', 'editor.admin_login': 'Accedi prima al pannello di amministrazione.', 'editor.not_found': 'Livello non trovato.',
    'editor.too_many': 'Hai raggiunto il numero massimo di livelli.', 'editor.draft_changed': 'Il livello è cambiato durante la prova: riprova.',
    'editor.status_local': 'solo su questo dispositivo', 'editor.status_draft': 'bozza', 'editor.status_published': 'pubblicato', 'editor.status_hidden': 'nascosto da un moderatore',
    tools: ['Terreno', 'Blocco di ghiaccio', 'Blocco moneta', 'Moneta', 'Piattaforma', 'Ghiaccio fragile', 'Spuntoni', 'Lava / acqua', 'Molla', 'Piattaforma mobile ↔', 'Piattaforma mobile ↕',
      'Blocco pesce', 'Blocco fiocco', 'Blocco ali', 'Blocco cuore', 'Checkpoint', 'Camminatore', 'Spinoso', 'Uccello', 'Saltatore', 'Ghiacciolo', 'Partenza', 'Traguardo (igloo)', 'Gomma', 'Sposta vista', 'Cartello'],
  },
  pt: {
    'community.title': 'Níveis da comunidade', 'community.search': 'Procurar', 'community.empty': 'Ainda não há níveis – cria o primeiro!', 'community.by': 'de {0}',
    'community.like': 'Gosto', 'community.report': 'Denunciar', 'community.report_reason': 'O que está errado neste nível?', 'community.reported': 'Obrigado, vamos verificar.',
    'community.login_needed': 'Entra para dar gosto (Opções → Conta online).', 'online.by_top': 'Mais gostados', 'online.by_new': 'Mais recentes', 'online.by_plays': 'Mais jogados',
    'editor.title': 'Editor de níveis', 'editor.new': 'Novo nível', 'editor.untitled': 'O meu nível', 'editor.rename': 'Nome do nível', 'editor.world': 'Mundo', 'editor.test': 'Testar',
    'editor.save': 'Guardar', 'editor.publish': 'Publicar', 'editor.saved': 'Guardado.', 'editor.saved_local': 'Guardado neste dispositivo. Entra para guardar online e publicar.',
    'editor.need_start': 'Coloca exatamente uma partida (pinguim).', 'editor.need_goal': 'Coloca exatamente uma meta (iglu).', 'editor.too_small': 'O nível deve ter pelo menos 20 casas de largura.',
    'editor.title_short': 'Dá um nome ao teu nível (pelo menos 3 caracteres).', 'editor.publish_info': 'Para publicar, joga o teu nível uma vez até à meta. Boa sorte!',
    'editor.published': 'Publicado! Todos podem jogar o teu nível.', 'editor.published_main': 'Nível principal publicado – ativo para todos.',
    'editor.not_finished': 'Não concluído – chega à meta para publicar.', 'editor.login_needed': 'Entra (Opções → Conta online) para guardar online e publicar.',
    'editor.testing': 'Teste', 'editor.test_ok': 'Meta alcançada – o teu nível é possível!', 'editor.hint': 'Esq.: colocar · Dir.: apagar · Roda/setas: deslocar',
    'editor.admin': 'Nível principal {0} (admin)', 'editor.admin_login': 'Entra primeiro no painel de administração.', 'editor.not_found': 'Nível não encontrado.',
    'editor.too_many': 'Atingiste o número máximo de níveis.', 'editor.draft_changed': 'O nível mudou durante o teste – testa novamente.',
    'editor.status_local': 'só neste dispositivo', 'editor.status_draft': 'rascunho', 'editor.status_published': 'publicado', 'editor.status_hidden': 'ocultado por um moderador',
    tools: ['Chão', 'Bloco de gelo', 'Bloco de moeda', 'Moeda', 'Plataforma', 'Gelo frágil', 'Espinhos', 'Lava / água', 'Mola', 'Plataforma móvel ↔', 'Plataforma móvel ↕',
      'Bloco peixe', 'Bloco floco', 'Bloco asas', 'Bloco coração', 'Checkpoint', 'Caminhante', 'Espinhoso', 'Pássaro', 'Saltador', 'Pingente de gelo', 'Partida', 'Meta (iglu)', 'Borracha', 'Mover vista', 'Placa'],
  },
  nl: {
    'community.title': 'Communitylevels', 'community.search': 'Zoeken', 'community.empty': 'Nog geen levels – bouw de eerste!', 'community.by': 'door {0}',
    'community.like': 'Vind ik leuk', 'community.report': 'Melden', 'community.report_reason': 'Wat is er mis met dit level?', 'community.reported': 'Bedankt, we kijken ernaar.',
    'community.login_needed': 'Log in om levels te liken (Opties → Online account).', 'online.by_top': 'Populairst', 'online.by_new': 'Nieuwste', 'online.by_plays': 'Meest gespeeld',
    'editor.title': 'Level-editor', 'editor.new': 'Nieuw level', 'editor.untitled': 'Mijn level', 'editor.rename': 'Naam van het level', 'editor.world': 'Wereld', 'editor.test': 'Testen',
    'editor.save': 'Opslaan', 'editor.publish': 'Publiceren', 'editor.saved': 'Opgeslagen.', 'editor.saved_local': 'Op dit apparaat opgeslagen. Log in om online op te slaan en te publiceren.',
    'editor.need_start': 'Plaats precies één start (pinguïn).', 'editor.need_goal': 'Plaats precies één doel (iglo).', 'editor.too_small': 'Het level moet minstens 20 vakjes breed zijn.',
    'editor.title_short': 'Geef je level een naam (minstens 3 tekens).', 'editor.publish_info': 'Om te publiceren speel je je level één keer uit. Succes!',
    'editor.published': 'Gepubliceerd! Iedereen kan je level nu spelen.', 'editor.published_main': 'Hoofdlevel gepubliceerd – actief voor alle spelers.',
    'editor.not_finished': 'Niet gehaald – bereik het doel om te publiceren.', 'editor.login_needed': 'Log in (Opties → Online account) om online op te slaan en te publiceren.',
    'editor.testing': 'Testrun', 'editor.test_ok': 'Doel bereikt – je level is haalbaar!', 'editor.hint': 'Links: plaatsen · Rechts: wissen · Wiel/pijlen: scrollen',
    'editor.admin': 'Hoofdlevel {0} (admin)', 'editor.admin_login': 'Log eerst in op het beheerpaneel.', 'editor.not_found': 'Level niet gevonden.',
    'editor.too_many': 'Je hebt het maximale aantal levels bereikt.', 'editor.draft_changed': 'Het level is tijdens de test gewijzigd – test opnieuw.',
    'editor.status_local': 'alleen op dit apparaat', 'editor.status_draft': 'concept', 'editor.status_published': 'gepubliceerd', 'editor.status_hidden': 'verborgen door een moderator',
    tools: ['Grond', 'IJsblok', 'Muntblok', 'Munt', 'Platform', 'Brokkelijs', 'Stekels', 'Lava / water', 'Veer', 'Bewegend platform ↔', 'Bewegend platform ↕',
      'Visblok', 'Sneeuwvlokblok', 'Vleugelblok', 'Hartblok', 'Checkpoint', 'Loper', 'Stekelige', 'Vogel', 'Springer', 'IJspegel', 'Start', 'Doel (iglo)', 'Gum', 'Beeld verschuiven', 'Bord'],
  },
  sv: {
    'community.title': 'Communitybanor', 'community.search': 'Sök', 'community.empty': 'Inga banor än – bygg den första!', 'community.by': 'av {0}',
    'community.like': 'Gilla', 'community.report': 'Anmäl', 'community.report_reason': 'Vad är fel med banan?', 'community.reported': 'Tack, vi tittar på det.',
    'community.login_needed': 'Logga in för att gilla banor (Alternativ → Onlinekonto).', 'online.by_top': 'Mest gillade', 'online.by_new': 'Nyaste', 'online.by_plays': 'Mest spelade',
    'editor.title': 'Baneditor', 'editor.new': 'Ny bana', 'editor.untitled': 'Min bana', 'editor.rename': 'Banans namn', 'editor.world': 'Värld', 'editor.test': 'Testa',
    'editor.save': 'Spara', 'editor.publish': 'Publicera', 'editor.saved': 'Sparat.', 'editor.saved_local': 'Sparat på den här enheten. Logga in för att spara online och publicera.',
    'editor.need_start': 'Placera exakt en start (pingvin).', 'editor.need_goal': 'Placera exakt ett mål (igloo).', 'editor.too_small': 'Banan måste vara minst 20 rutor bred.',
    'editor.title_short': 'Ge banan ett namn (minst 3 tecken).', 'editor.publish_info': 'För att publicera spelar du banan till målet en gång. Lycka till!',
    'editor.published': 'Publicerad! Alla kan spela din bana nu.', 'editor.published_main': 'Huvudbanan publicerad – aktiv för alla spelare.',
    'editor.not_finished': 'Inte klarad – nå målet för att publicera.', 'editor.login_needed': 'Logga in (Alternativ → Onlinekonto) för att spara online och publicera.',
    'editor.testing': 'Testkörning', 'editor.test_ok': 'Målet nått – banan går att klara!', 'editor.hint': 'Vänster: placera · Höger: sudda · Hjul/pilar: rulla',
    'editor.admin': 'Huvudbana {0} (admin)', 'editor.admin_login': 'Logga först in i adminpanelen.', 'editor.not_found': 'Banan hittades inte.',
    'editor.too_many': 'Du har nått max antal banor.', 'editor.draft_changed': 'Banan ändrades under testet – testa igen.',
    'editor.status_local': 'bara på den här enheten', 'editor.status_draft': 'utkast', 'editor.status_published': 'publicerad', 'editor.status_hidden': 'dold av en moderator',
    tools: ['Mark', 'Isblock', 'Myntblock', 'Mynt', 'Plattform', 'Sprött is', 'Spikar', 'Lava / vatten', 'Fjäder', 'Rörlig plattform ↔', 'Rörlig plattform ↕',
      'Fiskblock', 'Snöflingeblock', 'Vingblock', 'Hjärtblock', 'Checkpoint', 'Vandrare', 'Taggig', 'Fågel', 'Hoppare', 'Istapp', 'Start', 'Mål (igloo)', 'Suddgummi', 'Flytta vy', 'Skylt'],
  },
  pl: {
    'community.title': 'Poziomy społeczności', 'community.search': 'Szukaj', 'community.empty': 'Brak poziomów – zbuduj pierwszy!', 'community.by': 'autor: {0}',
    'community.like': 'Lubię to', 'community.report': 'Zgłoś', 'community.report_reason': 'Co jest nie tak z tym poziomem?', 'community.reported': 'Dziękujemy, sprawdzimy to.',
    'community.login_needed': 'Zaloguj się, aby polubić poziom (Opcje → Konto online).', 'online.by_top': 'Najbardziej lubiane', 'online.by_new': 'Najnowsze', 'online.by_plays': 'Najczęściej grane',
    'editor.title': 'Edytor poziomów', 'editor.new': 'Nowy poziom', 'editor.untitled': 'Mój poziom', 'editor.rename': 'Nazwa poziomu', 'editor.world': 'Świat', 'editor.test': 'Testuj',
    'editor.save': 'Zapisz', 'editor.publish': 'Opublikuj', 'editor.saved': 'Zapisano.', 'editor.saved_local': 'Zapisano na tym urządzeniu. Zaloguj się, aby zapisać online i opublikować.',
    'editor.need_start': 'Ustaw dokładnie jeden start (pingwin).', 'editor.need_goal': 'Ustaw dokładnie jeden cel (igloo).', 'editor.too_small': 'Poziom musi mieć co najmniej 20 pól szerokości.',
    'editor.title_short': 'Nazwij swój poziom (co najmniej 3 znaki).', 'editor.publish_info': 'Aby opublikować, przejdź swój poziom raz do celu. Powodzenia!',
    'editor.published': 'Opublikowano! Wszyscy mogą teraz grać w twój poziom.', 'editor.published_main': 'Poziom główny opublikowany – aktywny dla wszystkich.',
    'editor.not_finished': 'Nie ukończono – dojdź do celu, aby opublikować.', 'editor.login_needed': 'Zaloguj się (Opcje → Konto online), aby zapisać online i opublikować.',
    'editor.testing': 'Test', 'editor.test_ok': 'Cel osiągnięty – poziom jest do przejścia!', 'editor.hint': 'Lewy: stawiaj · Prawy: usuwaj · Kółko/strzałki: przewijaj',
    'editor.admin': 'Poziom główny {0} (admin)', 'editor.admin_login': 'Najpierw zaloguj się do panelu administracyjnego.', 'editor.not_found': 'Nie znaleziono poziomu.',
    'editor.too_many': 'Osiągnięto maksymalną liczbę poziomów.', 'editor.draft_changed': 'Poziom zmienił się podczas testu – przetestuj ponownie.',
    'editor.status_local': 'tylko na tym urządzeniu', 'editor.status_draft': 'szkic', 'editor.status_published': 'opublikowany', 'editor.status_hidden': 'ukryty przez moderatora',
    tools: ['Ziemia', 'Blok lodu', 'Blok z monetą', 'Moneta', 'Platforma', 'Kruchy lód', 'Kolce', 'Lawa / woda', 'Sprężyna', 'Ruchoma platforma ↔', 'Ruchoma platforma ↕',
      'Blok ryby', 'Blok płatka', 'Blok skrzydeł', 'Blok serca', 'Punkt kontrolny', 'Piechur', 'Kolczak', 'Ptak', 'Skoczek', 'Sopel', 'Start', 'Cel (igloo)', 'Gumka', 'Przesuń widok', 'Tabliczka'],
  },
  cs: {
    'community.title': 'Úrovně komunity', 'community.search': 'Hledat', 'community.empty': 'Zatím žádné úrovně – postav první!', 'community.by': 'od {0}',
    'community.like': 'Líbí se mi', 'community.report': 'Nahlásit', 'community.report_reason': 'Co je s touto úrovní špatně?', 'community.reported': 'Děkujeme, podíváme se na to.',
    'community.login_needed': 'Přihlas se, abys mohl dávat lajky (Možnosti → Online účet).', 'online.by_top': 'Nejoblíbenější', 'online.by_new': 'Nejnovější', 'online.by_plays': 'Nejhranější',
    'editor.title': 'Editor úrovní', 'editor.new': 'Nová úroveň', 'editor.untitled': 'Moje úroveň', 'editor.rename': 'Název úrovně', 'editor.world': 'Svět', 'editor.test': 'Otestovat',
    'editor.save': 'Uložit', 'editor.publish': 'Zveřejnit', 'editor.saved': 'Uloženo.', 'editor.saved_local': 'Uloženo v tomto zařízení. Přihlas se pro online uložení a zveřejnění.',
    'editor.need_start': 'Umísti přesně jeden start (tučňák).', 'editor.need_goal': 'Umísti přesně jeden cíl (iglú).', 'editor.too_small': 'Úroveň musí být široká alespoň 20 políček.',
    'editor.title_short': 'Pojmenuj svou úroveň (alespoň 3 znaky).', 'editor.publish_info': 'Pro zveřejnění dohraj svou úroveň jednou do cíle. Hodně štěstí!',
    'editor.published': 'Zveřejněno! Všichni teď mohou hrát tvou úroveň.', 'editor.published_main': 'Hlavní úroveň zveřejněna – aktivní pro všechny.',
    'editor.not_finished': 'Nedohráno – dojdi do cíle pro zveřejnění.', 'editor.login_needed': 'Přihlas se (Možnosti → Online účet) pro online uložení a zveřejnění.',
    'editor.testing': 'Test', 'editor.test_ok': 'Cíl dosažen – úroveň je zvládnutelná!', 'editor.hint': 'Levé: položit · Pravé: smazat · Kolečko/šipky: posun',
    'editor.admin': 'Hlavní úroveň {0} (admin)', 'editor.admin_login': 'Nejdřív se přihlas do administrace.', 'editor.not_found': 'Úroveň nenalezena.',
    'editor.too_many': 'Dosáhl jsi maximálního počtu úrovní.', 'editor.draft_changed': 'Úroveň se během testu změnila – otestuj znovu.',
    'editor.status_local': 'jen v tomto zařízení', 'editor.status_draft': 'koncept', 'editor.status_published': 'zveřejněno', 'editor.status_hidden': 'skryto moderátorem',
    tools: ['Zem', 'Ledový blok', 'Blok s mincí', 'Mince', 'Plošina', 'Křehký led', 'Bodáky', 'Láva / voda', 'Pružina', 'Pohyblivá plošina ↔', 'Pohyblivá plošina ↕',
      'Blok s rybou', 'Blok s vločkou', 'Blok s křídly', 'Blok se srdcem', 'Kontrolní bod', 'Chodec', 'Ostnáč', 'Pták', 'Skokan', 'Rampouch', 'Start', 'Cíl (iglú)', 'Guma', 'Posunout pohled', 'Cedule'],
  },
  tr: {
    'community.title': 'Topluluk bölümleri', 'community.search': 'Ara', 'community.empty': 'Henüz bölüm yok – ilkini sen yap!', 'community.by': '{0} tarafından',
    'community.like': 'Beğen', 'community.report': 'Bildir', 'community.report_reason': 'Bu bölümde sorun ne?', 'community.reported': 'Teşekkürler, kontrol edeceğiz.',
    'community.login_needed': 'Beğenmek için giriş yap (Seçenekler → Çevrimiçi hesap).', 'online.by_top': 'En beğenilen', 'online.by_new': 'En yeni', 'online.by_plays': 'En çok oynanan',
    'editor.title': 'Bölüm düzenleyici', 'editor.new': 'Yeni bölüm', 'editor.untitled': 'Bölümüm', 'editor.rename': 'Bölüm adı', 'editor.world': 'Dünya', 'editor.test': 'Test et',
    'editor.save': 'Kaydet', 'editor.publish': 'Yayınla', 'editor.saved': 'Kaydedildi.', 'editor.saved_local': 'Bu cihaza kaydedildi. Çevrimiçi kaydetmek ve yayınlamak için giriş yap.',
    'editor.need_start': 'Tam olarak bir başlangıç (penguen) koy.', 'editor.need_goal': 'Tam olarak bir bitiş (iglo) koy.', 'editor.too_small': 'Bölüm en az 20 kare genişliğinde olmalı.',
    'editor.title_short': 'Bölümüne bir ad ver (en az 3 karakter).', 'editor.publish_info': 'Yayınlamak için bölümünü bir kez bitişe kadar oyna. Bol şans!',
    'editor.published': 'Yayınlandı! Artık herkes bölümünü oynayabilir.', 'editor.published_main': 'Ana bölüm yayınlandı – tüm oyuncular için etkin.',
    'editor.not_finished': 'Bitirilmedi – yayınlamak için bitişe ulaş.', 'editor.login_needed': 'Çevrimiçi kaydetmek ve yayınlamak için giriş yap (Seçenekler → Çevrimiçi hesap).',
    'editor.testing': 'Deneme', 'editor.test_ok': 'Bitişe ulaşıldı – bölümün bitirilebilir!', 'editor.hint': 'Sol: yerleştir · Sağ: sil · Tekerlek/oklar: kaydır',
    'editor.admin': 'Ana bölüm {0} (yönetici)', 'editor.admin_login': 'Önce yönetim paneline giriş yap.', 'editor.not_found': 'Bölüm bulunamadı.',
    'editor.too_many': 'En fazla bölüm sayısına ulaştın.', 'editor.draft_changed': 'Bölüm test sırasında değişti – tekrar test et.',
    'editor.status_local': 'yalnızca bu cihazda', 'editor.status_draft': 'taslak', 'editor.status_published': 'yayında', 'editor.status_hidden': 'bir moderatör tarafından gizlendi',
    tools: ['Zemin', 'Buz bloğu', 'Para bloğu', 'Para', 'Platform', 'Kırılgan buz', 'Dikenler', 'Lav / su', 'Yay', 'Hareketli platform ↔', 'Hareketli platform ↕',
      'Balık bloğu', 'Kar tanesi bloğu', 'Kanat bloğu', 'Kalp bloğu', 'Kontrol noktası', 'Yürüyen', 'Dikenli', 'Kuş', 'Zıplayan', 'Buz sarkıtı', 'Başlangıç', 'Bitiş (iglo)', 'Silgi', 'Görünümü kaydır', 'Tabela'],
  },
  ru: {
    'community.title': 'Уровни сообщества', 'community.search': 'Поиск', 'community.empty': 'Пока нет уровней – создай первый!', 'community.by': 'автор: {0}',
    'community.like': 'Нравится', 'community.report': 'Пожаловаться', 'community.report_reason': 'Что не так с этим уровнем?', 'community.reported': 'Спасибо, мы проверим.',
    'community.login_needed': 'Войди, чтобы ставить лайки (Настройки → Онлайн-аккаунт).', 'online.by_top': 'Популярные', 'online.by_new': 'Новые', 'online.by_plays': 'Самые играемые',
    'editor.title': 'Редактор уровней', 'editor.new': 'Новый уровень', 'editor.untitled': 'Мой уровень', 'editor.rename': 'Название уровня', 'editor.world': 'Мир', 'editor.test': 'Тест',
    'editor.save': 'Сохранить', 'editor.publish': 'Опубликовать', 'editor.saved': 'Сохранено.', 'editor.saved_local': 'Сохранено на этом устройстве. Войди, чтобы сохранить онлайн и опубликовать.',
    'editor.need_start': 'Поставь ровно один старт (пингвин).', 'editor.need_goal': 'Поставь ровно одну цель (иглу).', 'editor.too_small': 'Уровень должен быть шириной не менее 20 клеток.',
    'editor.title_short': 'Дай уровню название (не менее 3 символов).', 'editor.publish_info': 'Чтобы опубликовать, пройди свой уровень один раз до цели. Удачи!',
    'editor.published': 'Опубликовано! Теперь все могут играть в твой уровень.', 'editor.published_main': 'Основной уровень опубликован – активен для всех.',
    'editor.not_finished': 'Не пройдено – дойди до цели, чтобы опубликовать.', 'editor.login_needed': 'Войди (Настройки → Онлайн-аккаунт), чтобы сохранять онлайн и публиковать.',
    'editor.testing': 'Тестовый забег', 'editor.test_ok': 'Цель достигнута – уровень проходим!', 'editor.hint': 'ЛКМ: поставить · ПКМ: стереть · Колесо/стрелки: прокрутка',
    'editor.admin': 'Основной уровень {0} (админ)', 'editor.admin_login': 'Сначала войди в панель администратора.', 'editor.not_found': 'Уровень не найден.',
    'editor.too_many': 'Достигнуто максимальное число уровней.', 'editor.draft_changed': 'Уровень изменился во время теста – протестируй снова.',
    'editor.status_local': 'только на этом устройстве', 'editor.status_draft': 'черновик', 'editor.status_published': 'опубликован', 'editor.status_hidden': 'скрыт модератором',
    tools: ['Земля', 'Ледяной блок', 'Блок с монетой', 'Монета', 'Платформа', 'Хрупкий лёд', 'Шипы', 'Лава / вода', 'Пружина', 'Движущаяся платформа ↔', 'Движущаяся платформа ↕',
      'Блок рыбы', 'Блок снежинки', 'Блок крыльев', 'Блок сердца', 'Контрольная точка', 'Ходок', 'Колючка', 'Птица', 'Прыгун', 'Сосулька', 'Старт', 'Цель (иглу)', 'Ластик', 'Сдвинуть вид', 'Табличка'],
  },
  el: {
    'community.title': 'Πίστες κοινότητας', 'community.search': 'Αναζήτηση', 'community.empty': 'Δεν υπάρχουν πίστες ακόμη – φτιάξε την πρώτη!', 'community.by': 'από {0}',
    'community.like': 'Μου αρέσει', 'community.report': 'Αναφορά', 'community.report_reason': 'Τι πρόβλημα έχει αυτή η πίστα;', 'community.reported': 'Ευχαριστούμε, θα το ελέγξουμε.',
    'community.login_needed': 'Συνδέσου για να κάνεις like (Επιλογές → Λογαριασμός online).', 'online.by_top': 'Πιο αγαπημένες', 'online.by_new': 'Νεότερες', 'online.by_plays': 'Πιο παιγμένες',
    'editor.title': 'Επεξεργαστής πιστών', 'editor.new': 'Νέα πίστα', 'editor.untitled': 'Η πίστα μου', 'editor.rename': 'Όνομα πίστας', 'editor.world': 'Κόσμος', 'editor.test': 'Δοκιμή',
    'editor.save': 'Αποθήκευση', 'editor.publish': 'Δημοσίευση', 'editor.saved': 'Αποθηκεύτηκε.', 'editor.saved_local': 'Αποθηκεύτηκε σε αυτή τη συσκευή. Συνδέσου για online αποθήκευση και δημοσίευση.',
    'editor.need_start': 'Βάλε ακριβώς μία αφετηρία (πιγκουίνος).', 'editor.need_goal': 'Βάλε ακριβώς έναν τερματισμό (ιγκλού).', 'editor.too_small': 'Η πίστα πρέπει να έχει πλάτος τουλάχιστον 20 τετράγωνα.',
    'editor.title_short': 'Δώσε όνομα στην πίστα (τουλάχιστον 3 χαρακτήρες).', 'editor.publish_info': 'Για δημοσίευση, τερμάτισε την πίστα σου μία φορά. Καλή επιτυχία!',
    'editor.published': 'Δημοσιεύτηκε! Όλοι μπορούν πλέον να την παίξουν.', 'editor.published_main': 'Η κύρια πίστα δημοσιεύτηκε – ενεργή για όλους.',
    'editor.not_finished': 'Δεν τερματίστηκε – φτάσε στον τερματισμό για δημοσίευση.', 'editor.login_needed': 'Συνδέσου (Επιλογές → Λογαριασμός online) για online αποθήκευση και δημοσίευση.',
    'editor.testing': 'Δοκιμαστική διαδρομή', 'editor.test_ok': 'Τερματισμός – η πίστα σου βγαίνει!', 'editor.hint': 'Αριστερό: τοποθέτηση · Δεξί: σβήσιμο · Ροδέλα/βέλη: κύλιση',
    'editor.admin': 'Κύρια πίστα {0} (διαχειριστής)', 'editor.admin_login': 'Συνδέσου πρώτα στον πίνακα διαχείρισης.', 'editor.not_found': 'Η πίστα δεν βρέθηκε.',
    'editor.too_many': 'Έφτασες τον μέγιστο αριθμό πιστών.', 'editor.draft_changed': 'Η πίστα άλλαξε κατά τη δοκιμή – δοκίμασε ξανά.',
    'editor.status_local': 'μόνο σε αυτή τη συσκευή', 'editor.status_draft': 'πρόχειρο', 'editor.status_published': 'δημοσιευμένη', 'editor.status_hidden': 'κρυμμένη από συντονιστή',
    tools: ['Έδαφος', 'Μπλοκ πάγου', 'Μπλοκ νομίσματος', 'Νόμισμα', 'Πλατφόρμα', 'Εύθραυστος πάγος', 'Αγκάθια', 'Λάβα / νερό', 'Ελατήριο', 'Κινούμενη πλατφόρμα ↔', 'Κινούμενη πλατφόρμα ↕',
      'Μπλοκ ψαριού', 'Μπλοκ νιφάδας', 'Μπλοκ φτερών', 'Μπλοκ καρδιάς', 'Σημείο ελέγχου', 'Περιπατητής', 'Αγκαθωτός', 'Πουλί', 'Πηδηχτός', 'Σταλακτίτης', 'Αφετηρία', 'Τερματισμός (ιγκλού)', 'Γόμα', 'Μετακίνηση προβολής', 'Πινακίδα'],
  },
  ja: {
    'community.title': 'コミュニティステージ', 'community.search': '検索', 'community.empty': 'まだステージがありません。最初の一つを作ろう！', 'community.by': '作者：{0}',
    'community.like': 'いいね', 'community.report': '報告', 'community.report_reason': 'このステージの問題は何ですか？', 'community.reported': 'ありがとうございます。確認します。',
    'community.login_needed': 'いいねするにはログインしてください（オプション → オンラインアカウント）。', 'online.by_top': '人気順', 'online.by_new': '新着順', 'online.by_plays': 'プレイ数順',
    'editor.title': 'ステージエディター', 'editor.new': '新しいステージ', 'editor.untitled': 'マイステージ', 'editor.rename': 'ステージ名', 'editor.world': 'ワールド', 'editor.test': 'テスト',
    'editor.save': '保存', 'editor.publish': '公開', 'editor.saved': '保存しました。', 'editor.saved_local': 'この端末に保存しました。オンライン保存と公開にはログインが必要です。',
    'editor.need_start': 'スタート（ペンギン）をちょうど1つ置いてください。', 'editor.need_goal': 'ゴール（イグルー）をちょうど1つ置いてください。', 'editor.too_small': 'ステージの幅は20マス以上必要です。',
    'editor.title_short': 'ステージに名前を付けてください（3文字以上）。', 'editor.publish_info': '公開するには、ステージを一度ゴールまでクリアしてください。がんばって！',
    'editor.published': '公開しました！だれでも遊べます。', 'editor.published_main': 'メインステージを公開しました。全プレイヤーに反映されます。',
    'editor.not_finished': 'クリアしていません。公開するにはゴールしてください。', 'editor.login_needed': 'オンライン保存と公開にはログインしてください（オプション → オンラインアカウント）。',
    'editor.testing': 'テストプレイ', 'editor.test_ok': 'ゴール！このステージはクリア可能です！', 'editor.hint': '左：置く · 右：消す · ホイール/矢印：スクロール',
    'editor.admin': 'メインステージ {0}（管理者）', 'editor.admin_login': '先に管理パネルにログインしてください。', 'editor.not_found': 'ステージが見つかりません。',
    'editor.too_many': 'ステージ数の上限に達しました。', 'editor.draft_changed': 'テスト中にステージが変更されました。もう一度テストしてください。',
    'editor.status_local': 'この端末のみ', 'editor.status_draft': '下書き', 'editor.status_published': '公開中', 'editor.status_hidden': 'モデレーターにより非表示',
    tools: ['地面', '氷ブロック', 'コインブロック', 'コイン', '足場', 'くずれる氷', 'トゲ', '溶岩／水', 'バネ', '動く足場 ↔', '動く足場 ↕',
      'サカナブロック', 'ユキブロック', 'ツバサブロック', 'ハートブロック', 'チェックポイント', 'ウォーカー', 'トゲトゲ', 'トリ', 'ホッパー', 'つらら', 'スタート', 'ゴール（イグルー）', '消しゴム', '表示を移動', '看板'],
  },
  zh: {
    'community.title': '社区关卡', 'community.search': '搜索', 'community.empty': '还没有关卡——来做第一个吧！', 'community.by': '作者：{0}',
    'community.like': '点赞', 'community.report': '举报', 'community.report_reason': '这个关卡有什么问题？', 'community.reported': '谢谢，我们会检查。',
    'community.login_needed': '登录后才能点赞（选项 → 在线账户）。', 'online.by_top': '最受欢迎', 'online.by_new': '最新', 'online.by_plays': '最多游玩',
    'editor.title': '关卡编辑器', 'editor.new': '新关卡', 'editor.untitled': '我的关卡', 'editor.rename': '关卡名称', 'editor.world': '世界', 'editor.test': '测试',
    'editor.save': '保存', 'editor.publish': '发布', 'editor.saved': '已保存。', 'editor.saved_local': '已保存在此设备上。登录后可在线保存并发布。',
    'editor.need_start': '请放置且仅放置一个起点（企鹅）。', 'editor.need_goal': '请放置且仅放置一个终点（冰屋）。', 'editor.too_small': '关卡宽度至少需要 20 格。',
    'editor.title_short': '给你的关卡起个名字（至少 3 个字符）。', 'editor.publish_info': '要发布，请先亲自通关一次。祝你好运！',
    'editor.published': '已发布！现在大家都能玩你的关卡了。', 'editor.published_main': '主线关卡已发布——对所有玩家生效。',
    'editor.not_finished': '未通关——到达终点才能发布。', 'editor.login_needed': '请登录（选项 → 在线账户）以在线保存和发布。',
    'editor.testing': '测试游玩', 'editor.test_ok': '到达终点——你的关卡可以通关！', 'editor.hint': '左键：放置 · 右键：擦除 · 滚轮/方向键：滚动',
    'editor.admin': '主线关卡 {0}（管理员）', 'editor.admin_login': '请先登录管理面板。', 'editor.not_found': '找不到关卡。',
    'editor.too_many': '你的关卡数量已达上限。', 'editor.draft_changed': '测试期间关卡已更改——请重新测试。',
    'editor.status_local': '仅在此设备', 'editor.status_draft': '草稿', 'editor.status_published': '已发布', 'editor.status_hidden': '已被管理员隐藏',
    tools: ['地面', '冰块', '金币方块', '金币', '平台', '易碎冰', '尖刺', '岩浆／水', '弹簧', '移动平台 ↔', '移动平台 ↕',
      '鱼方块', '雪花方块', '翅膀方块', '爱心方块', '检查点', '行走怪', '刺猬怪', '鸟', '跳跳怪', '冰柱', '起点', '终点（冰屋）', '橡皮擦', '移动视图', '告示牌'],
  },
  ko: {
    'community.title': '커뮤니티 레벨', 'community.search': '검색', 'community.empty': '아직 레벨이 없습니다. 첫 번째 레벨을 만들어 보세요!', 'community.by': '제작: {0}',
    'community.like': '좋아요', 'community.report': '신고', 'community.report_reason': '이 레벨에 어떤 문제가 있나요?', 'community.reported': '감사합니다. 확인하겠습니다.',
    'community.login_needed': '좋아요를 누르려면 로그인하세요 (옵션 → 온라인 계정).', 'online.by_top': '인기순', 'online.by_new': '최신순', 'online.by_plays': '플레이순',
    'editor.title': '레벨 에디터', 'editor.new': '새 레벨', 'editor.untitled': '내 레벨', 'editor.rename': '레벨 이름', 'editor.world': '월드', 'editor.test': '테스트',
    'editor.save': '저장', 'editor.publish': '공개', 'editor.saved': '저장했습니다.', 'editor.saved_local': '이 기기에 저장했습니다. 온라인 저장과 공개는 로그인 후 가능합니다.',
    'editor.need_start': '시작점(펭귄)을 정확히 하나 놓으세요.', 'editor.need_goal': '도착점(이글루)을 정확히 하나 놓으세요.', 'editor.too_small': '레벨은 최소 20칸 너비여야 합니다.',
    'editor.title_short': '레벨 이름을 지어 주세요 (3자 이상).', 'editor.publish_info': '공개하려면 레벨을 한 번 끝까지 클리어하세요. 행운을 빌어요!',
    'editor.published': '공개했습니다! 이제 모두가 플레이할 수 있습니다.', 'editor.published_main': '메인 레벨을 공개했습니다. 모든 플레이어에게 적용됩니다.',
    'editor.not_finished': '클리어하지 못했습니다. 공개하려면 도착점에 도달하세요.', 'editor.login_needed': '온라인 저장과 공개는 로그인이 필요합니다 (옵션 → 온라인 계정).',
    'editor.testing': '테스트 플레이', 'editor.test_ok': '도착! 이 레벨은 클리어할 수 있습니다!', 'editor.hint': '왼쪽: 놓기 · 오른쪽: 지우기 · 휠/화살표: 스크롤',
    'editor.admin': '메인 레벨 {0} (관리자)', 'editor.admin_login': '먼저 관리자 패널에 로그인하세요.', 'editor.not_found': '레벨을 찾을 수 없습니다.',
    'editor.too_many': '레벨 개수 한도에 도달했습니다.', 'editor.draft_changed': '테스트 중에 레벨이 바뀌었습니다. 다시 테스트하세요.',
    'editor.status_local': '이 기기에만', 'editor.status_draft': '초안', 'editor.status_published': '공개됨', 'editor.status_hidden': '관리자가 숨김',
    tools: ['땅', '얼음 블록', '코인 블록', '코인', '발판', '부서지는 얼음', '가시', '용암 / 물', '스프링', '움직이는 발판 ↔', '움직이는 발판 ↕',
      '물고기 블록', '눈송이 블록', '날개 블록', '하트 블록', '체크포인트', '걷는 적', '가시 적', '새', '뛰는 적', '고드름', '시작', '도착 (이글루)', '지우개', '화면 이동', '표지판'],
  },
};

for (const [code, texts] of Object.entries(L)) {
  const { tools, ...plain } = texts;
  if (tools.length !== TOOLS.length) throw new Error(`${code}: ${tools.length} tool names`);
  if (Object.keys(plain).length !== Object.keys(L.en).length - 1) throw new Error(`${code}: ${Object.keys(plain).length} texts, en has ${Object.keys(L.en).length - 1}`);
  const file = path.join(dir, `${code}.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  for (const [k, v] of Object.entries(plain)) if (!(k in data)) data[k] = v;
  TOOLS.forEach((t, i) => { if (!(`editor.tool.${t}` in data)) data[`editor.tool.${t}`] = tools[i]; });
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + '\n');
}
console.log(`editor texts added to ${Object.keys(L).length} languages`);
